version: '2'

services:

### Ghost Server Container ##################################

    ghost:
        image: ghost
        expose:
          - "2368"
        volumes:
          - ./ghost:/var/lib/ghost
        environment:            
            #Development
            NODE_ENV: development
            #Production
            #NODE_ENV: production

### Caddy Server Container ##################################

    caddy:
        image: abiosoft/caddy
        ports:
            - "80:80"
            - "443:443"
        volumes:
            #Development
            - ./caddy/Caddyfile.local:/etc/Caddyfile
            #Production
            #- ./caddy/Caddyfile:/etc/Caddyfile
            - ./caddy/.certs:/etc/caddycerts
            - ./logs/caddy:/var/log/caddy
        links:
            - ghost
        environment:
            CADDYPATH: /etc/caddycerts
